question_data = [
    [
        {"question": "A slug's blood is green.", "correct_answer": "True"},
        {"question": "The loudest animal is the African Elephant.", "correct_answer": "False"},
        {"question": "Approximately one quarter of human bones are in the feet.", "correct_answer": "True"},
        {"question": "The total surface area of a human lungs is the size of a football pitch.",
         "correct_answer": "True"},
        {"question": "In West Virginia, USA, if you accidentally hit an animal with your car, "
                     "you are free to take it home to eat.", "correct_answer": "True"},
        {"question": "In London, UK, if you happen to die in the House of Parliament, "
                     "you are entitled to a state funeral.", "correct_answer": "False"},
        {"question": "It is illegal to pee in the Ocean in Portugal.", "correct_answer": "True"},
        {"question": "You can lead a cow down stairs but not up stairs.", "correct_answer": "False"},
        {"question": "Google was originally called 'Backrub'.", "correct_answer": "True"},
        {"question": "Buzz Aldrin's mother's maiden name was 'Moon'.", "correct_answer": "True"},
        {"question": "No piece of square dry paper can be folded in half more than 7 times.",
         "correct_answer": "False"},
        {"question": "A few ounces of chocolate can kill a small dog.", "correct_answer": "True"}
    ],
    [
        {"category": "History", "type": "boolean", "difficulty": "easy",
         "question": "The Cold War ended with Joseph Stalin's death.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "Greenland is almost as big as Africa.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean",
         "difficulty": "easy",
         "question": "In Mario Kart 64, Waluigi is a playable character.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Politics", "type": "boolean", "difficulty": "easy",
         "question": "The S in Harry S. Truman stands for Samuel.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
         "question": "The 'Bernstein Bears' is the correct spelling of the educational children's book series name.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean",
         "difficulty": "easy",
         "question": "Donkey Kong was originally set to be a Popeye arcade game.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
         "difficulty": "easy",
         "question": "The anime 'Lucky Star' follows the story of one girl who is unaware she is God.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Animals", "type": "boolean", "difficulty": "easy",
         "question": "In 2016, the IUCN reclassified the status of Giant Pandas from endangered to vulnerable.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Animals", "type": "boolean", "difficulty": "easy",
         "question": "Rabbits are rodents.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
         "question": "In the movie The Revenant, DiCaprio's character hunts down the killer of his son.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "History", "type": "boolean", "difficulty": "easy",
         "question": "Adolf Hitler was tried at the Nuremberg trials.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean",
         "difficulty": "easy",
         "question": "Metal Gear Solid 3: Snake Eater was released in 2004.",
         "correct_answer": "True", "incorrect_answers": ["False"]}],
    [
        {"category": "Sports", "type": "boolean", "difficulty": "easy",
         "question": "Manchester United won the 2013-14 English Premier League.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "History", "type": "boolean", "difficulty": "easy",
         "question": "The United States Department of Homeland Security was formed in response "
                     "to the September 11th attacks.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
         "question": "In the original script of The Matrix, the machines used humans as "
                     "additional computing power instead of batteries.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In Kingdom Hearts the Paopu fruit is said to intertwine the destinies for two people forever.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Minecraft can be played with a virtual reality headset.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
         "question": "The alternative rock band, They Might Be Giants, released their album &#039;Flood&#039; in 1990.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
         "question": "In the original Star Wars trilogy, David Prowse was the actor who "
                     "physically portrayed Darth Vader.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
         "question": "In Battlestar Galactica (2004), Cylons were created by man as cybernetic workers and soldiers.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "History", "type": "boolean", "difficulty": "easy",
         "question": "Adolf Hitler was tried at the Nuremberg trials.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Watch_Dogs 2 is a prequel.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
         "question": "In Star Trek, Klaang is a typical Klingon male.",
         "correct_answer": "True", "incorrect_answers": ["False"]}]
]
